// <auto-generated />
namespace QuanLyNhanVien.Data.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.2.0-61023")]
    public sealed partial class CreatetableEmployeSalary : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(CreatetableEmployeSalary));
        
        string IMigrationMetadata.Id
        {
            get { return "201910010252060_CreatetableEmploye@Salary"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
